-- =====================================
-- 과일선물 상품 추가
-- =====================================

-- 1. 기존 선물 상품들 정리 (필요시)
-- DELETE FROM public.products WHERE category = 'gift';

-- 2. '달콤네 추천 실속세트 9과' 상품 추가
INSERT INTO public.products (
    store_id,
    name,
    price,
    quantity,
    image_url,
    is_soldout,
    category,
    created_at
) VALUES (
    1, -- 달콤네 강남점
    '달콤네 추천 실속세트 9과',
    53000,
    15,
    'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
    false,
    'gift',
    NOW()
);

-- 3. 확인용 쿼리
SELECT 
    p.id,
    s.name as store_name,
    p.name as product_name,
    p.price,
    p.quantity,
    p.category,
    p.is_soldout,
    p.created_at
FROM public.products p
JOIN public.stores s ON p.store_id = s.id
WHERE p.category = 'gift'
ORDER BY p.created_at DESC;

-- 4. 추가 정보를 위한 확장 테이블 생성 (필요시)
-- 과일선물 상품의 추가 정보 (할인가, 태그 등)를 저장하기 위한 테이블
CREATE TABLE IF NOT EXISTS public.gift_product_details (
    id bigint generated by default as identity primary key,
    product_id bigint references public.products(id) on delete cascade,
    original_price integer, -- 정가
    discount_rate integer, -- 할인율 (%)
    tags text[], -- 태그 배열
    rating numeric(2,1) DEFAULT 0, -- 평점 (0.0 ~ 5.0)
    review_count integer DEFAULT 0, -- 리뷰 수
    nutrition_info text, -- 영양 정보
    storage_info text, -- 보관 방법
    origin text, -- 원산지
    description_detail text, -- 상세 설명
    created_at timestamp default now()
);

-- 5. '달콤네 추천 실속세트 9과' 상세 정보 추가
INSERT INTO public.gift_product_details (
    product_id,
    original_price,
    discount_rate,
    tags,
    rating,
    review_count,
    nutrition_info,
    storage_info,
    origin,
    description_detail
) VALUES (
    (SELECT id FROM public.products WHERE name = '달콤네 추천 실속세트 9과' AND category = 'gift' LIMIT 1),
    59000, -- 정가
    10, -- 10% 할인
    ARRAY['추석특가', '혼합세트', '실속형'],
    4.8,
    34,
    '사과 5개, 배 4개 구성 - 비타민C, 식이섬유 풍부',
    '서늘하고 통풍이 잘 되는 곳에 보관, 냉장보관 권장',
    '국내산',
    '사과, 배 혼합세트로 당도가 높아서 맛있는 과일들로만 구성된 9과 상품입니다. 심혈을 기울여 준비한 추석 과일 세트입니다.'
);

-- 6. 과일선물 상품 전체 정보 조회 뷰 생성
CREATE OR REPLACE VIEW public.gift_products_view AS
SELECT 
    p.id,
    p.store_id,
    s.name as store_name,
    p.name,
    p.price,
    gpd.original_price,
    gpd.discount_rate,
    p.quantity,
    p.image_url,
    p.is_soldout,
    gpd.tags,
    gpd.rating,
    gpd.review_count,
    gpd.nutrition_info,
    gpd.storage_info,
    gpd.origin,
    gpd.description_detail,
    p.created_at
FROM public.products p
JOIN public.stores s ON p.store_id = s.id
LEFT JOIN public.gift_product_details gpd ON p.id = gpd.product_id
WHERE p.category = 'gift'
ORDER BY p.created_at DESC;

-- 7. 확인용: 전체 과일선물 상품 조회
SELECT * FROM public.gift_products_view;
