-- =====================================
-- 업데이트된 DB 테이블 설계 (과일선물 기능 추가)
-- =====================================

-- 1. 점포 테이블 (stores) - 기존과 동일
-- =====================================
create table public.stores (
    id bigint generated by default as identity primary key, -- 점포 ID
    name text not null, -- 점포 이름
    location text, -- 점포 위치 (주소)
    created_at timestamp default now()
);

-- =====================================
-- 2. 아파트 테이블 (apartments) - 기존과 동일
-- =====================================
create table public.apartments (
    id bigint generated by default as identity primary key, -- 아파트 단지 ID
    name text not null, -- 아파트 이름 (ex: 래미안 블루밍)
    address text, -- 도로명 주소 (선택)
    created_at timestamp default now()
);

-- =====================================
-- 3. 아파트 세대 테이블 (apartment_units) - 기존과 동일
-- =====================================
create table public.apartment_units (
    id bigint generated by default as identity primary key, -- 세대 ID
    apartment_id bigint references public.apartments(id) on delete cascade,
    dong text not null, -- 동
    ho text not null, -- 호
    created_at timestamp default now(),
    unique(apartment_id, dong, ho) -- 하나의 아파트 내 동/호 조합은 유일
);

-- =====================================
-- 4. 상품 테이블 (products) - ⭐ 업데이트됨
-- =====================================
create table public.products (
    id bigint generated by default as identity primary key,
    store_id bigint references public.stores(id) on delete cascade,
    name text not null, -- 상품명
    price integer not null, -- 가격 (원 단위)
    quantity integer not null, -- 재고 수량
    image_url text, -- 이미지 URL (Supabase Storage)
    is_soldout boolean default false,
    category text not null default 'today' check (category in ('today', 'gift')), -- ⭐ 추가: 상품 카테고리
    created_at timestamp default now()
);

-- =====================================
-- 5. 과일선물 상품 상세정보 테이블 - ⭐ 신규 추가
-- =====================================
create table public.gift_product_details (
    id bigint generated by default as identity primary key,
    product_id bigint references public.products(id) on delete cascade,
    original_price integer, -- 정가
    discount_rate integer, -- 할인율 (%)
    tags text[], -- 태그 배열 ['추석특가', '혼합세트', '실속형']
    rating numeric(2,1) DEFAULT 0, -- 평점 (0.0 ~ 5.0)
    review_count integer DEFAULT 0, -- 리뷰 수
    nutrition_info text, -- 영양 정보
    storage_info text, -- 보관 방법
    origin text, -- 원산지
    description_detail text, -- 상세 설명
    created_at timestamp default now()
);

-- =====================================
-- 6. 주문 테이블 (orders) - 기존과 동일
-- =====================================
create table public.orders (
    id bigint generated by default as identity primary key,
    store_id bigint references public.stores(id) on delete cascade,
    apartment_unit_id bigint references public.apartment_units(id) on delete restrict, -- 세대 참조
    customer_name text,
    customer_phone text,
    is_paid boolean default false,
    status text default '접수됨', -- 상태: 접수됨, 배달중, 완료 등
    created_at timestamp default now()
);

-- =====================================
-- 7. 주문 상세 항목 테이블 (order_items) - 기존과 동일
-- =====================================
create table public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade,
    product_id bigint references public.products(id),
    quantity integer not null,
    unit_price integer not null -- 주문 시점의 가격
);

-- =====================================
-- 8. 관리자 사용자 테이블 (profiles) - 기존과 동일
-- =====================================
create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    role text check (role in ('admin', 'manager')) not null,
    store_id bigint references public.stores(id), -- 관리하는 점포 ID
    created_at timestamp default now()
);

-- =====================================
-- 9. 인덱스 추가 (성능 최적화)
-- =====================================
CREATE INDEX IF NOT EXISTS products_category_idx ON public.products(category);
CREATE INDEX IF NOT EXISTS products_store_category_idx ON public.products(store_id, category);
CREATE INDEX IF NOT EXISTS gift_details_product_idx ON public.gift_product_details(product_id);

-- =====================================
-- 10. 과일선물 상품 조회용 뷰
-- =====================================
create or replace view public.gift_products_view as
select 
    p.id,
    p.store_id,
    s.name as store_name,
    p.name,
    p.price,
    gpd.original_price,
    gpd.discount_rate,
    p.quantity,
    p.image_url,
    p.is_soldout,
    gpd.tags,
    gpd.rating,
    gpd.review_count,
    gpd.nutrition_info,
    gpd.storage_info,
    gpd.origin,
    gpd.description_detail,
    p.created_at
from public.products p
join public.stores s on p.store_id = s.id
left join public.gift_product_details gpd on p.id = gpd.product_id
where p.category = 'gift'
order by p.created_at desc;

-- =====================================
-- 11. 기존 주문 조회용 뷰 (기존과 동일)
-- =====================================
create or replace view public.order_view as
select
    o.id as order_id, -- 주문 ID
    o.store_id,
    a.name as apartment_name, -- 아파트 이름
    au.dong as apartment_dong, -- 동
    au.ho as apartment_ho, -- 호
    o.customer_name,
    o.customer_phone,
    o.is_paid,
    o.status,
    o.created_at
from orders o
join apartment_units au on o.apartment_unit_id = au.id
join apartments a on au.apartment_id = a.id;

-- =====================================
-- 12. 샘플 데이터 추가 (개발용)
-- =====================================

-- 점포 데이터
INSERT INTO public.stores (name, location) VALUES 
('달콤네 강남점', '서울특별시 강남구 역삼동 123-45'),
('달콤네 홍대점', '서울특별시 마포구 홍대동 67-89'),
('달콤네 신촌점', '서울특별시 서대문구 신촌동 12-34');

-- 과일선물 상품 추가
INSERT INTO public.products (store_id, name, price, quantity, image_url, is_soldout, category)
VALUES (1, '달콤네 추천 실속세트 9과', 53000, 15, 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400', false, 'gift');

-- 과일선물 상품 상세정보 추가
INSERT INTO public.gift_product_details (
    product_id, original_price, discount_rate, tags, rating, review_count, 
    nutrition_info, storage_info, origin, description_detail
) VALUES (
    (SELECT id FROM public.products WHERE name = '달콤네 추천 실속세트 9과' LIMIT 1),
    59000, 
    10, 
    ARRAY['추석특가', '혼합세트', '실속형'],
    4.8,
    34,
    '사과 5개, 배 4개 구성 - 비타민C, 식이섬유 풍부',
    '서늘하고 통풍이 잘 되는 곳에 보관, 냉장보관 권장',
    '국내산',
    '사과, 배 혼합세트로 당도가 높아서 맛있는 과일들로만 구성된 9과 상품입니다. 심혈을 기울여 준비한 추석 과일 세트입니다.'
);
